backend:
  name: github
  repo: divall-simmons/Divall-Simmons-website
  branch: main
  auth_type: implicit
  base_url: https://api.github.com

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Jewellery","Watches","Ornamental","Furniture","Brass","Art"]}
      - {label: "Condition", name: "condition", widget: "string"}
      - {label: "Approx Age", name: "age", widget: "string"}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
